name: Tests

on: [push]
jobs:
  unit-test:
    name: Jest unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - run: npm i -g install-subset
    - run: npm run install:jest
    - run: npm test
      env:
        CI: true
    - name: Codecov
      uses: codecov/codecov-action@master

