name: Tests

on: [push]
jobs:
  unit-test:
    name: Jest unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i -g install-subset
    - run: npm run install:jest
    - run: npm test
      env:
        CI: true
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6

